### ISSUE TITLE
Improved documentation - how to use priority and template from file?

### ISSUE THREAD

**Issue by gitrequests** [shapecode/twig-template-event-bundle#5]
Hello.
Thanks for the great bundle!
---
### [Docs update]

How about updating the readme file to use priority and templates from file (not from string)?
For example:
```php
$event->addCode(
    '@App/Layout/Header/_search.html.twig', // <-- How to properly use a link to a template file?
    array(
        'world' => 'World'
    ),
    10 // <--- So is it correct to use priority?
);
```
---
And is it possible to use yaml configuration in Symfony?
For example like this (Or something similar):
```yaml
services:
   events:
      test:
         blocks:
            test_block:
              class: "@App/EventListener/TestTwigEventListener"
              template: "@App/Layout/Header/_search.html.twig"
              priority: 10
```
---
### [Feature request]
And if such a configuration is possible, then maybe it’s worth adding the “enabled” parameter to dynamically manage blocks through configurations?
```yaml
services:
   events:
      test:
         blocks:
            test_block:
              enabled: true # <-- This one?
              class: "@App/EventListener/TestTwigEventListener"
              template: "@App/Layout/Header/_search.html.twig"
              priority: 10
```
As an example of such an event configuration, I will give an example from one project (if you are interested), here is a link to the file with the event configuration:
https://github.com/Sylius/Sylius/blob/a0ad0d1e4c61ed8ec30bbb39e36184cb910736b2/src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml#L66C5-L66C11
